### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by cugu**

### CODE REVIEW

**Comment by cherue** [comment]
Let's get this done! We should get consent from all [contributors](https://github.com/kaitai-io/kaitai_struct_doc/graphs/contributors) to license their work under the [GNU Free Documentation License](https://en.wikipedia.org/wiki/GNU_Free_Documentation_License).

* [x] @generalmimon 
* [x] @koczkatamas 
* [x] @davidhicks 
* [x] @itchyny 
* [x] @cyco 
* [x] @arekbulski 
* [x] @valery1707 
* [x] @tlindner 
* [x] @khasanov 
* [x] @follower 
* [x] @dgelessus 
* [x] @cugu 
* [x] @Mingun 
* [x] @KOLANICH 
* [x] @GabriellaNicoleRamirez 
* [x] @AndrewCh 

Everybody mentioned: please leave a comment stating your approval or disapproval in this issue.

**Comment by davidhicks** [comment]
All my contributions can be your choice of: GNU Free Documentation License, Creative Commons Zero (CC0), Public Domain.

**Comment by Mingun** [comment]
My approval

**Comment by dgelessus** [comment]
I'm OK with this too.

**Comment by KOLANICH** [comment]
You can consider my contributions into this repo as licensed under CC0. IMHO FDL-1.3 is a copyleft licence, copyleft licences are instruments of copyright trolls and their purpose is copyright trolling and using it for intraspecific competition instead of cooperation. They are effectively proprietary to the ones not using them. Especially the copyleft licences designed by FSF and/or Stallman. Really free licenses are public-domain like. Ones using them say `F**k copyright` by doing this.

**Comment by ghost** [comment]
Sure, i approve of this change.

**Comment by khasanov** [comment]
My approval

**Comment by generalmimon** [comment]
I approve.

**Comment by follower** [comment]
AFAICT my only contribution is a one character typo fix that shouldn't fall under any copyright legislation I'm aware of: https://github.com/kaitai-io/kaitai_struct_doc/commits?author=follower 

But, for the sake of completeness, I consent to my contribution being licensed under the GNU Free Documentation License.

**Comment by GabriellaNicoleRamirez** [comment]
I approve

**Comment by valery1707** [comment]
I approve

**Comment by koczkatamas** [comment]
I approve

**Comment by tlindner** [comment]
I approve.

**Comment by cherue** [comment]
Still missing responses from @itchyny, @arekbulski and @AndrewCh. Maybe this ping will help.

**Comment by arekbulski** [comment]
I am no longer a maintainer here on Kaitai. Anyway, you may publish whatever little I contributed under any, however ridiculous, license you think of. GNU or otherwise.

**Comment by cherue** [comment]
This could be merged now.

@itchyny's commits ([overview](https://github.com/kaitai-io/kaitai_struct_doc/commits?author=itchyny)) [fix some typos](https://github.com/kaitai-io/kaitai_struct_doc/commit/564690d5cec62b4c6fb13288ce7171aae2ae70b9) and [describe](https://github.com/kaitai-io/kaitai_struct_doc/commit/59f7f5e446ca50c26f9a5c246d1f0d70cd14c2a0) some [facts](https://github.com/kaitai-io/kaitai_struct_doc/commit/65baa115955cce66bc0993bfafa0ddbbe0b32991) about the expression language.

@AndrewCh's single [commit](https://github.com/kaitai-io/kaitai_struct_doc/commit/4d208cb69373aafddf91710ff9fdd89b950cdfa0) fixes a bunch of typos.

I think it would be good to give it another couple of days but then merge if there is no response.

**Comment by arekbulski** [comment]
Okay, maybe not ANY license. Lets not get ridiculous. ^^. GNU or MIT will suffice.

**Comment by cherue** [comment]
I think this should be merged.

**Comment by AndrewCh** [comment]
Approve

**Comment by generalmimon** [comment]
I'm finally merging this, @itchyny is simply unreachable.

Thanks @cherue for putting it all together!

**Comment by itchyny** [comment]
Approved. Sorry for late response.

**Comment by AndrewCh** [comment]
ok

**Pull request merged**
